---
title: "Check Test Files and Default Fit Functions"
author: "Robert M Flight"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SIRM.FTMS.peakCharacterization)
library(parallel)
library(cowplot)
options(mc.cores = 12)
```

```{r useful_functions}
plot_models <- function(in_model){
  plot_data <- rbind(data.frame(mz = in_model$x[,1], sd = in_model$y, type = "org"),
                     data.frame(mz = in_model$x[,1], sd = in_model$fitted, type = "fit"))
  ggplot(plot_data, aes(x = mz, y = sd, color = type)) + geom_point()
}


get_model_data <- function(model_list){
  all_data <- lapply(seq(1, length(model_list)), function(in_model){
    rbind(data.frame(mz = model_list[[in_model]]$x[,1], sd = model_list[[in_model]]$fitted, type = "fit", model = as.character(in_model)),
          data.frame(mz = model_list[[in_model]]$x[,1], sd = model_list[[in_model]]$y, type = "sd", model = as.character(in_model)))
  })
  
  all_data <- do.call(rbind, all_data)
  all_data
}

get_n_point <- function(model_list){
  n_point <- lapply(seq(1, length(model_list)), function(in_model){
    data.frame(n = length(model_list[[in_model]]$x[,1]), model = as.character(in_model))
  })
  n_point <- do.call(rbind, n_point)
  n_point
}

get_model_sd <- function(model_list){
  all_sd <- lapply(seq(1, length(model_list)), function(in_model){
    data.frame(sd = model_list[[in_model]]$s, model = as.character(in_model))
  })
  all_sd <- do.call(rbind, all_sd)
  all_sd
}

calc_multiplier <- function(model){
  x_vals <- model$x[,1]
  y_vals <- model$fitted
  
  y_1 <- y_vals[1]
  y_ratio <- y_vals / y_1
  data.frame(mz = x_vals, sd = y_vals, sd_ratio = y_ratio)
}

check_convergence <- function(list_of_mpls){
  list_compare <- lapply(seq(1, length(list_of_mpls)), function(i_mpl){
    print(i_mpl)
    compare_mpl <- list_of_mpls[[i_mpl]]
    
    compare_to_others <- lapply(list_of_mpls, function(in_mpl){as.numeric(compare_master_peak_lists(compare_mpl, in_mpl))})
    compare_to_others <- as.data.frame(do.call(rbind, compare_to_others))
    compare_to_others$index <- seq(1, nrow(compare_to_others))
    #compare_to_others <- dplyr::filter(compare_to_others, index != i_mpl)
    compare_to_others <- dplyr::mutate(compare_to_others, is_match = V1 + V3 + V4 + V5)
    
    min_match <- min(compare_to_others$index[compare_to_others$is_match == 4])
    
    match_info <- data.frame(model = i_mpl, min = min_match, self = min_match == i_mpl)
    match_info$run <- 0
    if (min_match != i_mpl) {
      use_match <- compare_to_others[min_match:nrow(compare_to_others), "is_match"]
      rle_match <- rle(use_match)
      match_info$run <- max(rle_match$lengths) + 1
    }
    match_info
  })
  do.call(rbind, list_compare)
}

n_convergence <- function(correspondent_object){
  correspondent_object$n_iteration
}
```

```{r list_files}
all_files <- dir("test_files/mspl_files_defaults_fullrun_", full.names = TRUE)
```


```{r get_info}
file_info <- lapply(all_files, function(in_file){
  print(in_file)
  tmp_env <- new.env()
  load(in_file, envir = tmp_env)
  
  model_data <- get_model_data(tmp_env$peak_finder$correspondent_peaks$sd_models)
  
  model_sd <- get_model_sd(tmp_env$peak_finder$correspondent_peaks$sd_models)
  model_points <- get_n_point(tmp_env$peak_finder$correspondent_peaks$sd_models)
  
  model_convergence <- check_convergence(tmp_env$peak_finder$correspondent_peaks$all_master_peak_lists)
  
  list(file = basename(in_file),
       data = model_data,
       sd = model_sd,
       n_point = model_points,
       convergence = model_convergence,
       iteration_scan = data.frame(file = basename(in_file),
                                   n_iteration = tmp_env$peak_finder$correspondent_peaks$n_iteration,
       n_scan = length(tmp_env$peak_finder$scan_start),
       n_dr_scan = length(tmp_env$peak_finder$scan_dr_filter),
       n_ic_scan = length(tmp_env$peak_finder$scan_information_content),
       n_final_scan = length(tmp_env$peak_finder$scan_normalized)))
})
```

```{r}
ggplot(dplyr::filter(file_info[[1]]$data, type == "fit"), aes(x = mz, y = sd, color = model)) + geom_point()
ggplot(dplyr::filter(file_info[[2]]$data, type == "fit"), aes(x = mz, y= sd, color = model)) + geom_point()
ggplot(dplyr::filter(file_info[[3]]$data, type == "fit"), aes(x = mz, y= sd, color = model)) + geom_point()
ggplot(dplyr::filter(file_info[[4]]$data, type == "fit"), aes(x = mz, y= sd, color = model)) + geom_point()
ggplot(dplyr::filter(file_info[[5]]$data, type == "fit"), aes(x = mz, y= sd, color = model)) + geom_point()
```

```{r}
file_info[[1]]$sd

file_info[[2]]$sd

file_info[[3]]$sd
```

This is what typeing looks like without any options.

And now we turn on some of the Rmd options.

And now we see what happens if we change the theme.

And now that we have some outputs .... Is this still tolerable???

```{r}
new_function <- function(){
  this new function should do something really snazzy.
  maybe it should be named something really funny.
}
```

Is there any kind of slow down when we have the editor window popped out??
