---
title: "Process Test Files, fit 4"
author: "Robert M Flight"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(SIRM.FTMS.peakCharacterization)
library(parallel)
options(mc.cores = 12)
```

## Functions

### Filtering

```{r filtering_scans}
filter_scans <- function(raw_data){
  scan_times <- data.frame(scan = raw_data$scan_range, 
                           time = raw_data$raw_data@scantime[raw_data$scan_range])
  scan_times <- dplyr::mutate(scan_times, lag = time - lag(time), lead = lead(time) - time)
  scan_times <- dplyr::filter(scan_times, lag >= 4, lead >= 4)
  
  raw_data$set_scans(scan_range = scan_times$scan)
  raw_data
}
```


## Run Data

```{r}
use_files <- dir("test_files", full.names = TRUE, pattern = "mzML")
zip_save <- paste0("test_files/zip_files_", make.names(Sys.time()))

if (!dir.exists(zip_save)) {
  dir.create(zip_save)
}

rdata_save <- paste0("test_files/mspl_files_defaults_fullrun_", make.names(Sys.time()))
if (!dir.exists(rdata_save)) {
  dir.create(rdata_save)
}

zip_files <- mclapply(use_files, function(ifile) {
  out_file <- file.path(zip_save, gsub("mzML$", "zip", basename(ifile)))
  mspl_file <- file.path(rdata_save, gsub(".mzML$", "_peaklist.RData", basename(ifile)))
  
  out_file <- file.path(zip_save, gsub("mzML$", "zip", basename(ifile)))
  
  if (!file.exists(out_file)) {
    anal_ms <- AnalyzeMS$new(ifile, out_file = out_file, peak_finder = PeakFinder$new(raw_filter = filter_scans))
    anal_ms$peak_finder$vocal <- TRUE
    try(anal_ms$run_all())
  } else {
    message("file already exists, skipping!")
  }
  
  peak_finder <- anal_ms$peak_finder
  peak_finder$multi_scan <- NULL
  
  save(peak_finder, file = mspl_file)
  out_file
  
})
```

## Alternative Running

```{r other_test, eval = FALSE}
library(SIRM.FTMS.peakCharacterization)
mzml_file <- "tests/testthat/001UKNneg.mzML"
json_file <- "tests/testthat/001UKNneg.json"

anal_ms <- AnalyzeMS$new(mzml_file, json_file, out_file = "001UKNneg.zip", peak_finder = PeakFinder$new(raw_filter = filter_scans))
anal_ms$load_file()
anal_ms$peak_finder$raw_data <- anal_ms$zip_ms$raw_ms
anal_ms$peak_finder$apply_raw_filter()
anal_ms$peak_finder$create_multi_scan()
anal_ms$peak_finder$create_multi_scan_peaklist()
anal_ms$peak_finder$multi_scan_peaklist$remove_bad_resolution_scans()
anal_ms$peak_finder$multi_scan_peaklist$scan_indices
```

## Checking the Results

Now we need to check the results. We do two checks:

1. That the new peaks are identical to a previous set of peaks (if available)
2. That we can do peak correspondence across two samples

### Comparing to Previous

```{r define_sets, eval = FALSE}
prev_files <- dir("mspl_files_defaults_fullrun_X2017.05.22.12.57.25", full.names = TRUE)
curr_files <- dir("mspl_files_defaults_fullrun_X2017.07.03.16.11.15", full.names = TRUE)

prev_data <- lapply(prev_files, function(x){
  tmp_env <- new.env()
  load(x, envir = tmp_env)
  mpl <- tmp_env$peak_finder$correspondent_peaks$master_peak_list$clone(deep = TRUE)
  rm(tmp_env)
  mpl
})

names(prev_data) <- basename(prev_files)

curr_data <- lapply(curr_files, function(x){
  tmp_env <- new.env()
  load(x, envir = tmp_env)
  mpl <- tmp_env$peak_finder$correspondent_peaks$master_peak_list$clone(deep = TRUE)
  rm(tmp_env)
  mpl
})
names(curr_data) <- basename(curr_files)
```

```{r check_old_new, eval = FALSE} 
all.equal(prev_data[[1]], curr_data[[1]])
```

