---
title: "initial peakcomparisons"
author: "Robert M Flight <rflight79@gmail.com>"
date: "`r Sys.time()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{initial peakcomparisons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(ftmsComparePeaks)
library(dplyr)
```

# Single Files

```{r single_files}
mz_file <- "/home/rmflight/Projects/work/CESB/ftms.QC/mzML_exported/92Cpos.mzML"
xcal_file <- "/home/rmflight/Projects/work/CESB/ftms.QC/exported_noref/92Cpos.xlsx"
```

## Peaks

```{r get_peaks}
mz_avg <- import_mzML(mz_file)
mz_peaks <- pracma_findpeaks(mz_avg)

xcal_peaks <- import_xcalibur(xcal_file)
```

## XCAL - MZ

```{r xcal_mz}
xcal_mz <- find_closest_peaks(mz_peaks, xcal_peaks, "mz", "xcal")

filter(xcal_mz, mz_diff != 0, mz_diff <= 1e-3) %>% nrow()
nrow(xcal_peaks)
```

## MZ - XCAL

```{r mz_xcal}
mz_xcal <- find_closest_peaks(xcal_peaks, mz_peaks, "xcal", "mz")
filter(mz_xcal, mz_diff != 0, mz_diff <= 1e-3) %>% nrow()
```


## Find Peaks that are not Closest Peaks

We refine the closest peaks by finding those ones that don't have a closest match
between the two comparisons.

```{r refine_peaks}
xcal_mz_not_min <- refine_closest_list(xcal_mz)
mz_xcal_not_min <- refine_closest_list(mz_xcal)
```

## Match in Both

```{r match_both}
xcal_mz_keep <- filter(xcal_mz, !(s_peak %in% xcal_mz_not_min$not_min_s))
mz_xcal_keep <- filter(mz_xcal, !(s_peak %in% mz_xcal_not_min$not_min_s))

in_both <- unique(intersect(xcal_mz_keep$q_peak, mz_xcal_keep$s_peak))
length(in_both)

length(unique(xcal_mz_keep$s_peak))
length(unique(mz_xcal_keep$s_peak))
```

## How Many Have Big Differences?

```{r big_diffs}
length(unique(xcal_mz_keep$s_peak))
sum(filter(xcal_mz_keep, mz_diff != 0) %>% select(., mz_diff) %>% unlist() <= 1e-3)
```

## View Them

```{r check_peaks}
head(mz_xcal_not_min$not_min_s)
filter(mz_xcal, s_peak %in% seq(10, 13))
xcal_plot <- plot_peaks(filter(mz_xcal, s_peak %in% seq(10, 13)), mz_avg, 1e-4)
xcal_plot
```



