erf <- function(x){
  2 * pnorm(x * sqrt(2)) - 1
}

psi <- function(x){
  (1 / sqrt(2 * pi)) * exp(-.5 * (x^2))
}

Z <- function(x){
  1 - pnorm(x)
}

#' correct peak variance
#'
#' Given a variance observed from a truncated normal distribution, correct it
#' assuming that it should have had 100% observaionts
#'
#' @param observed_variance the observed **variance**
#' @param fraction  what fraction was it observed in
#'
#'
#' @references https://en.wikipedia.org/wiki/Truncated_normal_distribution
#'
#' @return corrected variance
#' @export
#'
#' @examples
#' @seealso correct_mean correct_peak
correct_variance <- function(observed_variance, fraction){
  if (fraction >= 1) {
    return(observed_variance)
  }
  x <- qnorm(1 - fraction)
  A <- (x * psi(x)) / Z(x)
  B <- (psi(x) / Z(x))^2

  # A <- (x * psi(x)) / fraction
  # B <- (psi(x) / fraction)^2

  corrected_variance <- observed_variance / fraction

  return(corrected_variance)
}


#' correct peak mean
#'
#' Given a corrected SD, corrects the mean assuming that it is the result of
#' a truncated normal distribution.
#'
#' @param observed_mean the observed mean
#' @param corrected_sd a corrected sd, generated by `correct_variance`
#' @param fraction the fraction of total observations
#'
#' @references https://en.wikipedia.org/wiki/Truncated_normal_distribution
#'
#' @return corrected mean
#' @export
#'
#' @examples
#' @seealso correct_peak correct_variance
correct_mean <- function(observed_mean, corrected_sd, fraction){
  if (fraction >= 1) {
    return(observed_mean)
  }
  x <- qnorm(1 - fraction)
  numerator <- corrected_sd * psi(x)
  denominator <- Z(x)
  corrected_mean <- observed_mean - (numerator / denominator)

  return(corrected_mean)

}


#' correct peak sd and mean
#'
#' Assuming that an observed mean (intensity) and sd are from a truncated normal distribution
#' that is truncated on one side only.
#'
#' @param observed_mean the observed mean
#' @param observed_sd the observed sd
#' @param n_observed how many observations went into this mean
#' @param n_should_observe how many observations *should* there have been?
#'
#' @references https://en.wikipedia.org/wiki/Truncated_normal_distribution
#'
#' @return data.frame, with corrected mean and sd
#' @export
#'
#' @seealso correct_mean correct_variance
#'
#' @examples
correct_peak <- function(observed_mean, observed_sd, n_observed, n_should_observe){
  percentage <- n_observed / n_should_observe
  corrected_sd <- sqrt(correct_variance(observed_sd^2, percentage))
  corrected_mean <- correct_mean(observed_mean, corrected_sd, percentage)
  return(data.frame(mean = corrected_mean, sd = corrected_sd))
}
